
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analisis;

/** CUP generated class containing symbol constants. */
public class simbolos {
  /* terminals */
  public static final int colornaranja = 41;
  public static final int suma = 32;
  public static final int puntos = 29;
  public static final int resta = 33;
  public static final int interrogacionC = 9;
  public static final int interrogacionA = 10;
  public static final int corcheteC = 8;
  public static final int corcheteA = 7;
  public static final int coma = 13;
  public static final int igual = 6;
  public static final int graficalinea = 25;
  public static final int ptcoma = 3;
  public static final int defGlobal = 16;
  public static final int colorrojo = 39;
  public static final int colornegro = 43;
  public static final int EOF = 0;
  public static final int nombre = 26;
  public static final int error = 1;
  public static final int color = 27;
  public static final int entero = 37;
  public static final int colorazul = 42;
  public static final int tkstring = 14;
  public static final int por = 34;
  public static final int dospuntos = 2;
  public static final int graficabarras = 24;
  public static final int llaveC = 5;
  public static final int colorverde = 44;
  public static final int id = 17;
  public static final int llaveA = 4;
  public static final int galeria = 31;
  public static final int tituloy = 20;
  public static final int titulox = 19;
  public static final int tk_idedntificador = 38;
  public static final int titulo = 18;
  public static final int grosor = 28;
  public static final int defxyline = 30;
  public static final int parC = 12;
  public static final int parA = 11;
  public static final int coloramarillo = 40;
  public static final int puntosxy = 23;
  public static final int tkint = 15;
  public static final int div = 35;
  public static final int ejey = 22;
  public static final int ejex = 21;
  public static final int cadena = 36;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "dospuntos",
  "ptcoma",
  "llaveA",
  "llaveC",
  "igual",
  "corcheteA",
  "corcheteC",
  "interrogacionC",
  "interrogacionA",
  "parA",
  "parC",
  "coma",
  "tkstring",
  "tkint",
  "defGlobal",
  "id",
  "titulo",
  "titulox",
  "tituloy",
  "ejex",
  "ejey",
  "puntosxy",
  "graficabarras",
  "graficalinea",
  "nombre",
  "color",
  "grosor",
  "puntos",
  "defxyline",
  "galeria",
  "suma",
  "resta",
  "por",
  "div",
  "cadena",
  "entero",
  "tk_idedntificador",
  "colorrojo",
  "coloramarillo",
  "colornaranja",
  "colorazul",
  "colornegro",
  "colorverde"
  };
}

